AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
    - bin/**/*
    - config/boot.rb
    - db/schema.rb
    - script/**/*
    - tmp/**/*
    - vendor/**/*
    - Rakefile
    - Gemfile
    - Gemfile.lock
    - lib/**/*
    - db/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
  DisplayCopNames: true
Rails:
  Enabled: true
Style/ClassAndModuleChildren:
  Enabled: false
Layout/SpaceBeforeComma:
  Enabled: false
Layout/SpaceBeforeSemicolon:
  Enabled: false
Style/Alias:
  Enabled: false
Style/BeginBlock:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Documentation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Metrics/MethodLength:
  Max: 400
Metrics/ClassLength:
  Max: 400
Rails/ReversibleMigration:
  Enabled: false
Rails/FilePath:
  Enabled: false
Naming/FileName:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Metrics/BlockLength:
  Max: 100
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*'
Layout/TrailingBlankLines:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 30
Metrics/PerceivedComplexity:
  Max: 30
Style/Next:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Metrics/ParameterLists:
  Max: 8
Metrics/ModuleLength:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
Style/NestedParenthesizedCalls:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
Lint/ImplicitStringConcatenation:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Layout/AlignHash:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/UnneededInterpolation:
  Enabled: false
Style/RedundantParentheses:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Layout/SpaceInsideStringInterpolation:
  Enabled: false
Rails/ReadWriteAttribute:
  Enabled: false
Style/ParenthesesAroundCondition:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
